version: '3.3'

volumes:
  postgresql_data:

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/api
    ports:
      - 7779:7779
    depends_on:
      - db

  db:
    image: postgres:latest
    volumes:
      - postgresql_data:/data/db
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=mydatabase
    ports:
      - 5432:5432